### ISSUE TITLE
Update material-ui version and i18n support

### ISSUE THREAD

**Issue by ShirasawaSama** [baymac/material-ui-cron#1]
Can you update the version of `material-u`i to `5.0`?

![image](https://user-images.githubusercontent.com/17093811/126079879-878b7ff5-a3ba-4ba3-913a-93d8d17fa761.png)

In addition, can you add a localize API?

**Comment by baymac** [comment]
Hey @ShirasawaSama it makes sense to address both features request. I will find sometime this week to work on these issues. If you are interested to send a pr, feel free to do that. :)

**Comment by ShirasawaSama** [comment]
@baymac I hope you can design the localization API, and I will submit the language translation.

**Comment by ShirasawaSama** [comment]
In addition, I would like to remove the title:

![image](https://user-images.githubusercontent.com/17093811/126187835-0c605e70-bfb2-44f3-a2ae-ea0cb7f42470.png)

**Comment by baymac** [comment]
@ShirasawaSama 

1. I can work on the localization but can take some time, I will try this week.
2. Yes it makes sense to remove the header.

**Comment by ShirasawaSama** [comment]
@baymac Thank you!
