### ISSUE TITLE
Add @emotion/react @emotion/styled as dependency

### ISSUE THREAD

**Issue by baymac** [baymac/material-ui-cron#10]
**Describe the bug**
@emotion/react @emotion/styled should be added to dependency now that we have moved to material-ui/core-5.0.0-beta.1

**To Reproduce**
1. Create a new cra project
2. Run command `yarn add material-ui-cron@0.1.0-beta.2`
3. Add scheduler component in App.js
4. Run dev server `yarn start`

Server throws error 
```
./node_modules/@material-ui/styled-engine/index.js
Module not found: Can't resolve '@emotion/react' in '/path/to/dir/test/my-app/node_modules/@material-ui/styled-engine'
```

**Solution**
Add @emotion/react @emotion/styled to dependencies list.

**Comment by baymac** [comment]
@ShirasawaSama what do you think?

**Comment by ShirasawaSama** [comment]
I think it should be `peerDependencies`:

```json
"peerDependencies": {
  "@emotion/react": "*",
  "@emotion/styles": "*"
}
```

**Comment by baymac** [comment]
@ShirasawaSama peerDependencies are added just to match
