### ISSUE TITLE
TypeScript definition files are not included

### ISSUE THREAD

**Issue by ShirasawaSama** [baymac/material-ui-cron#6]
**Describe the bug**
The TypeScript definition (`*.d.ts`) files are not included.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/17093811/126362178-b84ade0c-ab5f-4d3d-92a3-3e6c6e4b6743.png)

**Desktop (please complete the following information):**

**Additional context*

Url: https://registry.npmjs.org/material-ui-cron/-/material-ui-cron-0.1.0-beta.1.tgz

**Comment by baymac** [comment]
@ShirasawaSama it is included for commonjs but not for esm. I am not sure why you do not get it on your machine build.
<img width="248" alt="Screenshot 2021-07-21 at 12 20 05 PM" src="https://user-images.githubusercontent.com/23079344/126444285-f29580f5-0aa9-474b-a0fb-aab039f5ac84.png">

**Comment by baymac** [comment]
I think there was some build issue in 0.1.0-beta.1 version. You can find types in next version https://registry.npmjs.org/material-ui-cron/-/material-ui-cron-0.1.0-beta.2.tgz.

**Comment by ShirasawaSama** [comment]
Awesome! The current version perfectly solves this problem.
